import type { NextPage } from 'next'
import Head from 'next/head'
import { Heading, Box } from '@chakra-ui/react'

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box as="main" bgColor="primary.500">
        <Heading as="h1">Se vienen cositas</Heading>
      </Box>
    </Box>
  )
}

export default Home
