import type { NextPage } from 'next'
import Head from 'next/head'
import { Heading, Box } from '@chakra-ui/react'

const Home: NextPage = () => {
  return (
    <Box
      display="flex"
      flexDirection="column"
      justifyContent="center"
      alignItems="center"
      minHeight="100vh"
      paddingY="0"
      paddingX="2"
    >
      <Head>
        <title>No hay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box as="main">
        <Heading as="h1" fontSize="6xl">
          Se vienen cositas
        </Heading>
      </Box>
    </Box>
  )
}

export default Home
